CREATE DATABASE CANVAS;

USE CANVAS;

CREATE TABLE CLIENTE(
NOME_COMPLETO VARCHAR(30),
CPF VARCHAR(11),
EMAIL VARCHAR(30),
SENHA VARCHAR(30));

CREATE TABLE metodo_pagamento (
    id_metodoPag INT AUTO_INCREMENT PRIMARY KEY,
    nome_metodoPag VARCHAR(100) NOT NULL
);

ALTER TABLE cliente
ADD PRIMARY KEY (CPF);

ALTER TABLE CLIENTE
ADD COLUMN FK_ID_PAGAMENTO int,
ADD CONSTRAINT fk_cliente_metodopag FOREIGN KEY(FK_ID_PAGAMENTO) 
REFERENCES metodo_pagamento(id_metodoPag);

INSERT INTO metodo_pagamento (nome_metodoPag)
VALUES ('Cartão de Crédito');
ALTER TABLE cliente
ADD PRIMARY KEY (CPF);



